name: alquran_tafsir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.0.3
  http: 0.13.5
  just_audio: 0.9.31
  lottie: 2.2.0
  path_provider: 2.0.12
  sqflite: ^2.2.4+1
  scroll_to_index: 3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/al-quran.png"

flutter:
  assets:
    - assets/lottie/
    - assets/images/purple.png
    - assets/images/gold.png
  uses-material-design: true
